### ISSUE TITLE
error Couldn't find package "wix-code-codemodel"

### ISSUE THREAD

**Issue by dhruvdutt** [wix/wix-code-ide#5]
While cloning locally and doing `yarn` or `npm install`

> error Couldn't find package "wix-code-codemodel" on the "npm" registry.

**Comment by ohana54** [comment]
Hi @dhruvdutt, sorry for the late response. This project is not ready yet for outside contribution, only accepting issues.
We are working to replace the current engine with Microsoft's Monaco IDE, and we will deprecate this project.
In the meantime, if you have any problems, please open a new issue. Thanks!
